# Generated by Django 2.2.2 on 2019-07-21 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nyan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='name',
            new_name='breed',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='owner',
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(default='gray', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='img_url',
            field=models.CharField(default='http://pm1.narvii.com/6605/5502c24ad2783c9a7998d84b192155bbd0ea7ddf_00.jpg', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nyan.Cat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
