# Generated by Django 2.2.2 on 2019-07-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nyan', '0002_auto_20190721_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercat',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
